apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-recomender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playlist-recommender
  template:
    metadata:
      labels:
        app: playlist-recommender
    spec:
      ## Server Container ##
      containers:
      - name: cloud-server-1
        image: leoomaia/server_cloud
        imagePullPolicy: Always
        ports:
        - containerPort: 32196
        volumeMounts:
        - name: persistent-volume
          mountPath: /app/models
      ## ML Container ##
      initContainers:
      - name: cloud-ml-1
        image: leoomaia/ml_cloud
        imagePullPolicy: Always
        volumeMounts:
        - name: persistent-volume
          mountPath: /app/models
      ## Persistent Volume ##
      volumes:
      - name: persistent-volume
        persistentVolumeClaim:
          claimName: project2-pv-leonardomaia