apiVersion: v1

kind: PersistentVolumeClaim
metadata:
  namespace: leonardomaia
  name: project-volume-leonardomaia
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: local