apiVersion: v1

kind: PersistentVolumeClaim
metadata:
  namespace: leonardomaia
  name: project2-pv-leonardomaia
  labels:
    type: local
spec:
  resources:
    requests:      
      storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  volumeName: project2-pv-leonardomaia