name: builde Machine Learning

on:
  push:
    paths:
      - Train_model/*
jobs: 
  build-deploy-server:
    runs-on: ubuntu-latest
    steps:
      - name: Check repository
        uses: actions/checkout@v3
      
      - name: User and Token for Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.CLOUDTP2_USERNAME }}
          password: ${{ secrets.CLOUDTP2_TOKEN }}
    
      - name: Build and Push image to change Machine Learning container
        uses: docker/build-push-action@v4
        with:
          context: Train_model/
          push: true
          tags: leoomaia/ml_cloud